### ISSUE TITLE
Seems like you're building a Text UI, do you know this Project? https://github.com/elw00d/consoleframework

### ISSUE THREAD

**Issue by SpocWeb** [adamabdelhamed/PowerArgs#113]
Hi, this Project is not from me, but it seems pretty advanced:
https://github.com/elw00d/consoleframework
It builds a Text UI, similar to TurboVision (Borland), but by parsing XAML. 
It also supports Value Binding.
Maybe you find it useful...
Best Regards...
Matthias

**Comment by adamabdelhamed** [comment]
Thanks.  Mine also parses a XAML like structure, but that path is not tested enough to document yet.  The whole PowerArgs.Cli namespace is a work in progress, and has been for a long time coming.  

But it is getting into pretty good shape.  I even went a little overboard and integrated a light physics engine I built a while ago.  You can see an in console shooter demo in this (also work in progress) project:
https://github.com/adamabdelhamed/ConsoleZombies
