### ISSUE TITLE
Null reference exception is thrown when running REPLInvoke sample and immediately quitting

### ISSUE THREAD

**Issue by hoochharp** [adamabdelhamed/PowerArgs#120]
If you run the REPLInvoke sample (or any REPL app) and simply type 'quit' as the very first thing you do, a null reference exception is thrown in Args.cs line 546 

      private static ArgAction<T> Strongify<T>(ArgAction weak)
        {
            return new ArgAction<T>()
            {
                Args = (T)weak.Value,
                ActionArgs = weak.ActionArgs,
                ActionArgsProperty = weak.ActionArgsProperty,
                ActionParameters = weak.ActionParameters,
                ActionArgsMethod = weak.ActionArgsMethod,
                HandledException = weak.HandledException,
                Definition = weak.Definition,
                Context = weak.Context,
                Cancelled = weak.Cancelled,
            };
        }
The parameter 'weak' is null but used anyway when creating a new ArgAction.

**Comment by adamabdelhamed** [comment]
Fixed in version 3.0
