### ISSUE TITLE
Support CancellationToken for Async Calls

### ISSUE THREAD

**Issue by Jaben** [adamabdelhamed/PowerArgs#121]
First of all: thanks for the great framework!

One request: Async arg actions should support cancellation tokens -- and that should be linked to the CTRL+V as well.

**Comment by adamabdelhamed** [comment]
Can you please give me an example of the code you would like to be able to write?

**Comment by RobertoPrevato** [comment]
Hi @adamabdelhamed,
I have the same case.

For example, I am creating a NET Core 2 console application that authenticates to Azure Active Directory using `Microsoft.IdentityModel.Clients.ActiveDirectory`. I am using the built-in method `AcquireDeviceCodeAsync`, which requires the user to open a browser window and insert a code to complete login, exactly like the official `azure-cli 2.0` implemented in Python and written by Microsoft works.

During this time, the console application is hanging (waiting for the user to complete login in the browser) - as a side note in NET Core there is no UI and no interactive way, at the moment, to perform login (cfr. [https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/885](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/885))

While the console app is waiting, I would like to be able to cancel the operation, if the user clicks "CTRL+C" and resume the main program loop.

Does PowerArgs support this scenario? Cancelling an action invoked with `Args.InvokeAction` and going back to the main loop?

**Comment by RobertoPrevato** [comment]
@Jaben 
@adamabdelhamed 

After further investigation, the library already supports cancellation tokens, there is nothing to change in it, in my opinion. I think this issue should be closed, and I don't think the CTRL+C combination should be handled out of the box inside PowerArgs.

This is a working example - I also tested with a login scenario -:

```cs
using PowerArgs;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace PowerArgsTest
{
    [ArgExceptionBehavior(ArgExceptionPolicy.StandardExceptionHandling), TabCompletion(REPL = true, HistoryToSave = 10)]
    internal class Program
    {
        [HelpHook]
        [ArgShortcut("-?")]
        [ArgDescription("Shows this help")]
        public bool Help { get; set; }

        [ArgActionMethod]
        [ArgDescription("Prints information about the application")]
        public void Info()
        {
            Console.WriteLine("Lorem ipsum dolor sit amet");
        }

        [ArgActionMethod]
        [ArgDescription("Wait a bit")]
        public void Wait()
        {
            try
            {
                _cancellationTokenSource = new CancellationTokenSource();
                var token = _cancellationTokenSource.Token;

                Console.WriteLine("... waiting 5 seconds - Click CTRL+C to cancel the operation!");

                Task.Run(() => Task.Delay(5000), token).Wait(token);

                Console.WriteLine("... done");
            }
            catch (OperationCanceledException)
            {
                Console.WriteLine("User cancelled");
            }
            catch (Exception e)
            {
                HandleException(e);
            }
        }

        private static CancellationTokenSource _cancellationTokenSource;

        static int Main(string[] args)
        {
            Console.CancelKeyPress += (sender, e) =>
            {
                if (_cancellationTokenSource != null)
                {
                    _cancellationTokenSource.Cancel();
                    _cancellationTokenSource = null;
                }
                e.Cancel = true;
            };

            try
            {
                Args.InvokeAction<Program>(args);
            }
            catch (Exception e)
            {
                HandleException(e);
                return 1;
            }
            return 0;
        }

        private static void HandleException(Exception ex)
        {
            if (ex is AggregateException aex)
            {
                foreach (Exception exception in aex.InnerExceptions)
                {
                    Console.WriteLine(exception.Message);
                }
            }

            Console.WriteLine(ex.Message);
        }
    }
}

```

**Comment by Jaben** [comment]
@RobertoPrevato Looks good to me. I ended up using a similar design.

Thank you much for your effort on this library. It's appreciated.
