### ISSUE TITLE
workaround to replace argument -user with --user

### ISSUE THREAD

**Issue by zinwalin** [adamabdelhamed/PowerArgs#122]
--user or -u is convention on Linux,  but PowerArgs uses -user or -u.  Currently, I can't change the called command options from --user to -user,  is there any easy way to support --user as well?

**Comment by adamabdelhamed** [comment]
Use [ArgShortcut("--user")] and [ArgShortcut(ArgShortcutPolicy.ShortcutsOnly)]

**Comment by psibernetic** [comment]
Seems like a good item for a FAQ!
