### ISSUE TITLE
Is there any way change the tpl language？

### ISSUE THREAD

**Issue by woaiwhr001** [adamabdelhamed/PowerArgs#123]
![tim 20171101213356](https://user-images.githubusercontent.com/20886053/32277159-813e61c6-bf4c-11e7-9c22-1c06004f8eec.png)

how can i change this with my language? is there any way?
我的英语不太好，请见谅。

**Comment by adamabdelhamed** [comment]
[You can use this method](https://github.com/adamabdelhamed/PowerArgs/blob/24a877f1fd14fef415f617f1a6cc516291783417/PowerArgs/ArgUsage.cs#L261) which accepts a custom template. 

The default template is [here](https://github.com/adamabdelhamed/PowerArgs/blob/24a877f1fd14fef415f617f1a6cc516291783417/PowerArgs/Resources/DefaultConsoleUsageTemplate.txt). You can modify it to be in your language.
