### ISSUE TITLE
NOT ISSUE - How to generate HTML Help instead of Console - Just a Question

### ISSUE THREAD

**Issue by akshayjoyinfo** [adamabdelhamed/PowerArgs#125]
How to generate HTML Help instead of Console

I have used Console Help for now, that I dont know how to generate HELP from HTML which you provided in Resources folder.

**Comment by adamabdelhamed** [comment]
Like this

var browserOutput = ArgUsage.GenerateUsageFromTemplate(type, template: UsageTemplates.BrowserTemplate);

**Comment by akshayjoyinfo** [comment]
awesome thanks..
