### ISSUE TITLE
PromptIfMissing and If/IfNot combination not working

### ISSUE THREAD

**Issue by NoBuddyHH** [adamabdelhamed/PowerArgs#126]
When you define an argument with

ArgRequired(PromptIfMissing = true, If = "Something")

and you run the program with that argument missing (but "Something" specified), it correctly prompts for the missing argument.

However, the entered argument value is not passed to the program.

I have (among others) the following to argmuents defined:
 
    [ArgRequired(IfNot = "Mode | Path", PromptIfMissing = true), ArgShortcut("-f")]
    public string File { get; set; }

    [ArgRequired(PromptIfMissing = true, If = "File"), ArgShortcut("-l")]
    public string FileLabel { get; set; }

If i start the program with no arguments specified, it correctly prompts for both argmuents.
But Args.Parse<ApplicationArguments>(args) does not populate the entered values....

Could you please have a look?

Regards
Denis

**Comment by adamabdelhamed** [comment]
published
