### ISSUE TITLE
HelpHook and generated help not working after using dotnet publish command

### ISSUE THREAD

**Issue by RobertoPrevato** [adamabdelhamed/PowerArgs#127]
Hi,
After using the dotnet publish command for a NET Core application using PowerArgs, the generated help doesn't work because the resources files are not copied.

This is what gets displayed instead of the generated help:
```
-?
Resources\DefaultConsoleUsageTemplate.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;iso-8859-1
```

**This looks like a bug in dotnet publish command, not within PowerArgs**, however PowerArgs could be simplified by simply using string constants for the two help templates (plain text and html) instead of *.resx* files, since these resources are not really culture dependent (am I wrong?).

I could prepare a pull request, if you agree with this.

Best Regards,
Roberto

**Comment by adamabdelhamed** [comment]
No problem. I just did it.

**Comment by adamabdelhamed** [comment]
published
