### ISSUE TITLE
Variable arg shortcuts?

### ISSUE THREAD

**Issue by kdubau** [adamabdelhamed/PowerArgs#139]
I am looking to add a global argument to my tool to control logging verbosity. I would like to use `mytool.exe -v` or `mytool.exe -vvv` for more verbose logging.

I have not figured out how with PowerArgs this can be achieved. Do you have any thoughts or ideas to accomplish it with the current implementation?

**Comment by adamabdelhamed** [comment]
Try this:

```cs
    [ArgShortcut("vvv")]
    [ArgShortcut("v")]
    [ArgShortcut(ArgShortcutPolicy.ShortcutsOnly)]
    public bool Verbose { get; set; }
```

**Comment by kdubau** [comment]
@adamabdelhamed I would need to be able to detect if the user did `-v` or `-vvv` to apply different settings.

**Comment by adamabdelhamed** [comment]
Hmmm, that's a good one. You can do something like [this](https://github.com/adamabdelhamed/PowerArgs/blob/master/PowerArgsTestCore/Core/WhichShortcutTest.cs).

It's a bit primitive, but hopefully you get the point.
