### ISSUE TITLE
Slash (/) with positional arguments running on Linux & MacOS

### ISSUE THREAD

**Issue by BlackFrog1** [adamabdelhamed/PowerArgs#147]
On Unix based operating system traditionally command-line options consist of a dash (-). On Windows , slash(/) have been it's standard.  

Using the absolute path to a file with positional arguments doesn't parse correctly on linux.
![Annotation 2020-04-22 173228](https://user-images.githubusercontent.com/550820/80036287-7254c700-84bf-11ea-9e34-22e1a7406ba4.png)

**Comment by BlackFrog1** [comment]
Here is my sample code I used to test my changes
https://gist.github.com/BlackFrog1/b113af22d79c016bcd2b27070b7f2653

And the output:
![Annotation 2020-04-22 175310](https://user-images.githubusercontent.com/550820/80037738-2f482300-84c2-11ea-9260-f318a57f6ea8.png)

**Comment by adamabdelhamed** [comment]
Thanks for the PR, but I found a way to address the issue more holistically and with fewer side effects. I'll push this the next time I make a release to nuget.
