### ISSUE TITLE
How to specify command line parameters with double dashes (eg. --help)

### ISSUE THREAD

**Issue by joltcoder** [adamabdelhamed/PowerArgs#149]
I want to adhere to the "cloud" standard of specifying command line parameters with two dashes instead of one. Is this possible with PowerArgs currently?

**Comment by adamabdelhamed** [comment]
You can specify a shortcut [as shown here](https://github.com/adamabdelhamed/PowerArgs/blob/d91eb6411bcc6975892871e136cf29d3e791a518/PowerArgsTestCore/Core/ShortcutTests.cs#L62).
