### ISSUE TITLE
New Release Pending?

### ISSUE THREAD

**Issue by mthierba** [adamabdelhamed/PowerArgs#152]
I can see some new functionality added to AliasCollection in c550ebbbcc4 which is not yet available in the latest release on NuGet: https://www.nuget.org/packages/PowerArgs/3.6.0
Is there a plan/date for the latest changes to go into a new public release?

**Comment by adamabdelhamed** [comment]
I'm on a sabbatical from my main job right now. I'm going to push out a new release in the coming weeks.
