### ISSUE TITLE
Prompting for input despite PromptIfMissing=false on Required arg

### ISSUE THREAD

**Issue by bc3tech** [adamabdelhamed/PowerArgs#154]
Whenever I run my app w/o any parameters, it appears to be launching into a CLI to which it expects the user to type argument parameters.
I have one `HelpHook` defined, one _required_ parameter defined, and all the other parameters have `ArgDefaultValue` specified (so they are optional).

What I'd rather have happen in this case is an error saying a parameter wasn't specified, but am not finding a way to make this happen.

Any ideas?

**Comment by bc3tech** [comment]
I just found and discovered `PromptIfMissing` on `ArgRequired` but that doesn't appear to be having any effect when I set it to `false`.

**Comment by bc3tech** [comment]
This was the only way I was able to get the behavior I wanted, despite setting `PromptIfMissing` on my single required arg to `false`:

```csharp
        class MyArgHook : ArgHook
        {
            public override void BeforeValidateDefinition(HookContext context)
            {
                context.Definition.IsNonInteractive = true;

                base.BeforeValidateDefinition(context);
            }
```

This seems way too heavy-handed IMO so I think we've got a bug here.

**Comment by adamabdelhamed** [comment]
I just tried this and it did not prompt me. I'll re-open if you can share a repro.

```cs
using PowerArgs;
public class Program
{
    public static void Main(string [] args) => Args.Parse<MyArgs>(args);
}

public class MyArgs
{
    [ArgRequired(PromptIfMissing = false)]
    public string Foo { get; set; }
}
```
