### ISSUE TITLE
How to parse into an array?

### ISSUE THREAD

**Issue by brandonh-msft** [adamabdelhamed/PowerArgs#156]
I thought by defining the arg as `List<T>` I would be able to do something like `-arg item1 -arg item2` but I'm met with an error that `-arg` has already been specified. Is there an option/metadata I'm missing?

**Comment by adamabdelhamed** [comment]
Using a list is supported, but it doesn't let you repeat the argument as you've tried. You would have to do this:

```
-arg "item1,item2,item3"
```

**Comment by brandonh-msft** [comment]
what if my values are strings and contain `,`?
