### ISSUE TITLE
Issue with scrolling in console

### ISSUE THREAD

**Issue by jenkstom** [adamabdelhamed/PowerArgs#157]
When the command is at the top of the screen, the usage information shows up just fine. If the screen is already full, the usage text doesn't display properly, they just overwrite each other and you only see a single line.

![image](https://user-images.githubusercontent.com/5612487/206752594-04f1737d-d259-405c-bea6-ddacb19913ab.png)

**Comment by adamabdelhamed** [comment]
Fix coming soon.

**Comment by adamabdelhamed** [comment]
Fixed in 4.0.1
