### ISSUE TITLE
Request: hide a parameter from the usage screen

### ISSUE THREAD

**Issue by nsulikowski** [adamabdelhamed/PowerArgs#37]
This would be for "hidden" "secret" parameters, that I want parsed, but not displayed in the usage print out.
Perhaps an attribute [ArgHidden] or something like that...

**Comment by jafz** [comment]
It seems to have been renamed. I landed here thrice while searching for this. I use those attributes:
OmitFromUsageDocs, ArgShortcut(ArgShortcutPolicy.NoShortcut)
The first arg prevents printing it, the second prevents it to collide with automatic shortcut letters.
