### ISSUE TITLE
Provide better formatting for long descriptions

### ISSUE THREAD

**Issue by dhilgarth** [adamabdelhamed/PowerArgs#49]
Long descriptions are not handled properly:

http://screencast.com/t/GKGF3CJS6ZN

**Comment by Geraint87** [comment]
I'm using version 2.5.10.1 and it doesn't seem to be indenting the lines either:

`ArgUsage.GenerateUsageFromTemplate<ApplicationArgs>().WriteLine();`

![image](https://cloud.githubusercontent.com/assets/5928208/6217384/2e0eea40-b60b-11e4-9b92-84af9a441e7a.png)
