### ISSUE TITLE
Multiple ArgActionType attributes or multiple Types in the attribute

### ISSUE THREAD

**Issue by jigamiller** [adamabdelhamed/PowerArgs#57]
I would like to see support for the deferred action methods to be placed in multiple, separate classes which should promote better separation of concerns and cleaner code.

In other words doing this:

``` csharp
[ArgActionType(AActions)]
[ArgActionType(BActions)]
public class MainActions { ... }

public class AActions { ... }
public class BActions { ... }
```

Or allow for multiple types in a single attribute such as:

``` csharp
[ArgActionType(AActions, BActions)]
public class MainActions { ... }

public class AActions { ... }
public class BActions { ... }
```

**Comment by romblu** [comment]
Hi Adam
Could you provide some examples on how to use dependency injection in the overridden ArgActionResolver class, please?

**Comment by jigamiller** [comment]
Actually, I got swamped at work and didn't get a chance to try it out yet
(sigh). I will see if I can free up some of my time in the near future to
give it a go.

John

**Comment by romblu** [comment]
Thanks John, I'm looking forward to hearing from you. :)
