### ISSUE TITLE
ITabCompletion is obsolete but TabCompletionAttribute requires it

### ISSUE THREAD

**Issue by mover5** [adamabdelhamed/PowerArgs#61]
I tried implementing a custom tab completion which implements ITabCompletionSource. This was marked as obsolete and it recommended I use ISmartTabCompletionSource. Doing so however, throws a runtime error:

Additional information: Type ARMApiCaller.Utilities.SubscriptionIdTabCompletion does not implement ITabCompletionSource

So in order to use the Smart features, I have to also implement ITabCompletion. I've tracked the offending code to here:
https://github.com/adamabdelhamed/PowerArgs/blob/6dee615f52d37c285925537cc29d6f75b1cb040b/PowerArgs/Hooks/TabCompletion.cs#L142

**Comment by adamabdelhamed** [comment]
Hey Mark,

That is in fact a bug.  I'll fix it.  As a workaround you can use the ArgumentAwareTabCompletionAttribute attribute if you want to have tab completion on a specific argument.  Put this attribute on any argument property and pass in your ISmartTabCompletionSource type.  It should work in that context.

Thanks,
Adam

**Comment by adamabdelhamed** [comment]
Reopening until it's published.

**Comment by adamabdelhamed** [comment]
published
