### ISSUE TITLE
Question: Is there anyway to make SecureStringArgument optional?

### ISSUE THREAD

**Issue by ristaloff** [adamabdelhamed/PowerArgs#64]
I would like my program to prompt the user for a password only if the -p option is set.
Is this possible? 
I tried this:
```
    [ArgShortcut("p") ,ArgDescription("Database password")]
    public SecureStringArgument DbPassword { get; set; }
```
And I get prompted for a password even if i don't pass -p as a parameter. 
I get promptet when I run `DbPassword.SecureString == null` to check if it was provided as an argument. Perhaps the SecureStringArgument should have a flag that can be checked to see if the SecureString is set or not, so I don't have to trigger the prompt.

I worked around the issue by doing this: 
    
    [ArgShortcut("p") ,ArgDescription("Get prompted for database password")]
    public bool PromptForPassword { get; set; }

    public SecureStringArgument DbPassword { get; set; }
Now I just check if PromptForPassword is set before I access DbPassword.SecureString.

**Comment by adamabdelhamed** [comment]
Hi,

The way you worked around this is the way I would recommend doing it.  Basically, you get prompted only if you inspect the SecureString property.  Having a flag that tells you to inspect that property and prompt the user is a clean pattern that I would recommend.

Thanks,
Adam

**Comment by ristaloff** [comment]
Ok, thanks.
I kind of found the solution while typing my question :)

Henrik
