### ISSUE TITLE
InvokeMain swallows all errors into: "Exception has been thrown by the target of an invocation."

### ISSUE THREAD

**Issue by Geraint87** [adamabdelhamed/PowerArgs#65]
I think this is what is happening. I have:

```
try
{
	Args.InvokeMain<ApplicationArgs>(args);
}
catch (Exception ex)
{
	Console.WriteLine(ex.Message);
	ArgUsage.GenerateUsageFromTemplate<ApplicationArgs>().WriteLine();
}
```
And wherever an error is thrown, the text displayed is the reflection-looking message.

If I dig into the inner exceptions I can get to the real message.

**Comment by adamabdelhamed** [comment]
I used to unwrap the inner exception and throw it explicitly, but then you lose the stack trace of the real exception.  I think this might be the right way to do this, but I'll look into it.  I'll leave this open until I ensure I'm using best practices for exception handling in these types of scenarios.

**Comment by taschmidt** [comment]
I just ran into this too.  If only supporting .net 4.5 is an option, this is the right way to do it:

ExceptionDispatchInfo.Capture(ex.InnerException).Throw();

http://stackoverflow.com/a/17091351

**Comment by Geraint87** [comment]
Any updates or suggestions for this?
I'm still having all of my exceptions surfacing as "Exception has been thrown by the target of an invocation."

**Comment by adamabdelhamed** [comment]
I'll fix this soon.  Sorry for the delay.

**Comment by adamabdelhamed** [comment]
I fixed this in several places.  Hopefully I got them all.  Let me know if I missed anything.
