### ISSUE TITLE
ArgPrefixAttribute for argument class

### ISSUE THREAD

**Issue by isolaol** [adamabdelhamed/PowerArgs#67]
Hi Adam,

I would like to control the prefixes of the argument names via single attribute (ArgPrefix, for example) that can be attached to the argument class.

This is what I write now:
```csharp
public class MyArgs {

    [ArgShortcut("s")]
    [ArgShortcut("--long")]
    public string StringArg { get; set; }

}
```
The example above enables a user to use four different argument names to feed value to program:
```
-s value
--long value
-StringArg value
/StringArg:value
```
The ArgPrefixAttribute(string short_name_prefix, string long_name_prefix) would allow myself to write:
```csharp
[ArgPrefix("-", "--")]
public class MyArgs {

    [ArgShortcut("s")]
    [ArgShortcut("long")]
    public string StringArg { get; set; }

}
```
The example above should make possible to use these forms of arguments:
```
-s value
--long value
--StringArg value
/StringArg:value
```
Please note that in the presense of ArgPrefixAttribute the library would pick the appropriate (allowed) prefix accoding the length of the ArgShortcut name argument (or property name). In the example, "s" is single character --> use "-" as prefix and "long" is longer than one char --> use "--" as prefix. Also, I do not need to add "--" in the beginning of the long name (ie. [ArgShortcut("--long")] became [ArgShortcut("long")]), which makes the code look clean.

The missing ArgPrefix would mean that current defaults ("-" prefix for every shortcut and arguments inferred from properties) name would be used.

If you like to think it a little bit furher... You could also allow developer to switch on and off /StringArg:value style and allow developer to pass his or her preferred separator ("=" instead of ":") if you add two more parameters to the ArgPrefix attribute, namely "bool dos_style" and "char dos_style_separator".

Kind regards,
Olli-Pekka Isola

**Comment by adamabdelhamed** [comment]
In general, I'm all for adding something at the class level that makes you have to write less code on each property, but I'm not sure this pattern is worth it.  Can I ask why you'd want to restrict users from using whatever format they want? An earlier version of PowerArgs did let the developer choose between -name value and /name:value, but I decided to just allow both all the time and let the end user decide which style they prefer. 

And I sort of like that you opt into the long form style '--' by adding the prefix explicitly to the shortcut.  

Can you please elaborate a little bit more on what benefits you're trying to get both in terms of developer productivity and/or end user experience?  I'm always willing to add features to this project, but I want to see clear value in them.

Thanks,
Adam
