### ISSUE TITLE
ArgRequired(false) enums are defaulted to zero when not specified

### ISSUE THREAD

**Issue by Toeboy** [adamabdelhamed/PowerArgs#69]
Hello,

If I have an enum that is optional and it's not specified in the command line, it defaults to 0 instead of null.
I changed the enums to nullable enums and it seem to default to null now. Is this the suggested usage?

Thanks!
TB

**Comment by adamabdelhamed** [comment]
That is the correct pattern.

**Comment by Toeboy** [comment]
Hello Adam,

It seems the nullable enums do not get outputed in the template. For example:

This property:
public TraceLevel TraceLevel { get; set; }

With this template:
{{if argument.ArgumentType.IsEnum}}
{{each enumVal in argument.EnumValuesAndDescriptions}}
{{enumVal!}}
!{{each}}
!{{if}}

Would output:
Off,Error,Warning,Info,Verbose

Same property but nullable:
public TraceLevel? TraceLevel { get; set; }

Would not output anything with the same template. Is this normal?

Thanks for this amazing library. The template engine is amazing!

Alex

**Comment by adamabdelhamed** [comment]
This is now fixed
