### ISSUE TITLE
How to manage dynamic number of args when files are drag&dropped on link/shortcut?

### ISSUE THREAD

**Issue by Paramethod** [adamabdelhamed/PowerArgs#72]
I have some executable with various options. I save a shortcut on desktop pointing to the executable and add the desired options at the end of the target field in the shortcut definition. Now if I double click the shortcut it will properly execute with the specified options. But if I drag and drop files on the shortcut, now I have an unknown number of arguments, because it appends one argument for each file dropped. How can I manage this dynamic list of added args?

Thanks,
TB

**Comment by adamabdelhamed** [comment]
I haven't supported that in the past, but it's a frequent ask so I'll do it.  Sorry for the delay.

**Comment by adamabdelhamed** [comment]
Ok.  I just checked into the dev branch.  Here's how this will work.

1 - Add the [ArgPosition(0)] attribute to your 'files' argument.  This tells PowerArgs that the first thing you expect on the command line is a collection of files which is what Windows will do when you drag a file over your program.
        Note that if your program takes actions as the first argument you'll need to do more than this.
2 - Make sure your 'files' argument is either an array or a List<string>.  These are the two collection formats that PowerArgs supports.

That's it!
