### ISSUE TITLE
Override Baked In Revivers with Custom Revier 

### ISSUE THREAD

**Issue by pcKris** [adamabdelhamed/PowerArgs#77]
Currently trying to implement a custom reviver that would take the place of the DateTime reviver.
After setting this up seems like this may not be an option. Currently working around it by creating my own class to wrap DateTime and then setting up a reviver for that object type. Will know if this works in shortly but dont see why it wouldnt.

Just wondering if there is already a way to or if you would be willing to add the ability to provide custom revivers that take the place of current revivers.

Some use cases

Bool: I would like to be able to accept  T/F || Y/N || 1/0 || Yes/No ........
DateTime: I would like to be able to accept "today" || "yesterday" || last week........

If i can get a moment to resolve this I will and set up a pull request, again thank you for this AWESOME lib, makes our lives here so much easier!

**Comment by pcKris** [comment]
Looks Like we could do this with a small change to the ArgRevivers.cs making some small logical changes at like 175:

Think instead of skipping revivers that already exists we could remove the existing one and add the one found. Thoughts?

```
foreach (var reviver in revivers)
                {
                    var r = reviver;
                    if (ArgRevivers.Revivers.ContainsKey(r.ReturnType) == false)
                    {
                        ArgRevivers.Revivers.Add(r.ReturnType, (key, val) =>
                        {
                            return r.Invoke(null, new object[] { key, val });
                        });
                    }
                }
```

**Comment by pcKris** [comment]
Looks like the proposed approach above would also require logic changes at line 37 would have to move the call to SearchAssembly (see below).
I could see how this may have a negative impact on overall performance, going to see what I can do about adding a registration method instead.

Args.Revivers.RegisterNew(Func<string,string,object> reviver, bool replaceIfExists=true)



```
        public static bool CanRevive(Type t)
        {
            // this would keep the system from ever discovering the custom reviver we are trying to replace the existing one with
            if (Revivers.ContainsKey(t) ||
                t.IsEnum ||
                (t.GetInterfaces().Contains(typeof(IList)) && t.IsGenericType && CanRevive(t.GetGenericArguments()[0])) ||
                (t.IsArray && CanRevive(t.GetElementType())))
                return true;
            SearchAssemblyForRevivers(t.Assembly);

            if (System.ComponentModel.TypeDescriptor.GetConverter(t).CanConvertFrom(typeof(string))) return true;

            return Revivers.ContainsKey(t);
        }
```

**Comment by adamabdelhamed** [comment]
I've been behind on this project, but I'll take a look at this soon.

**Comment by adamabdelhamed** [comment]
Which tests are failing for you?  I don't have any failing on my machine.  Some http pipeline tests are failing on my CI setup, but those are related to a preview feature (and live in the Preview namespace) that isn't really intended for widespread use yet.  

I'm going to take a look right now at the reviver code and make this possible.

**Comment by adamabdelhamed** [comment]
The IsBool method is needed because it allows for the special syntax where a bool will be set to true even if the user doesn't specify a value. 

For example:
myApp                                <--------- somebool will be false
myApp -somebool true      <--------- somebool will be true
myApp -somebool false      <--------- somebool will be false
myApp -somebool                <--------- somebool will be true (special syntax that requires IsBool)

I'm curious as to what issue you saw with this though.  Can you please share?

Thanks,
Adam

**Comment by adamabdelhamed** [comment]
You can now override the built in revivers.  If you're using the attribute then this should just start working for you.

Note that I also added ArgRevivers.SetReviver() so you can do this imperatively as well.

**Comment by Geraint87** [comment]
I can't get the "auto-overriding" to work.
I've created a reviver for DateTime (as I usually want to use DateTime.ParseExact on the string entered instead of Parse). I believe it has the right signature for an ArgReviver, and it's in the same assembly as the Main(string[] args) entry point, but the method doesn't get hit.

If I use ArgRevivers.SetReviver to set it declaritavely, then it works fine.

Reviver below.

```
[ArgReviver]
public static DateTime StrictDateTimeReviver(string key, string value)
{
	try
	{
		return DateTime.ParseExact(value, "yyyyMMdd", CultureInfo.InvariantCulture);
	}
	catch
	{
		throw new ArgException("Date is in the incorrect format.");
	}
}
```

**Comment by pcKris** [comment]
I have experienced the same issue. Used the same work around

-Chris

**Comment by adamabdelhamed** [comment]
I'll probably fix the current batch of issues sometime in December when I have some time. Thanks for reporting.

Sent from my Windows Phone
________________________________
