### ISSUE TITLE
Invalid action invokes previous action in REPL session

### ISSUE THREAD

**Issue by 3bit** [adamabdelhamed/PowerArgs#85]
If an invalid action is specified within a REPL session no exception is thrown and the previous action gets invoked.

I will issue a merge request with a test that reproduces the problem shorty.

**Comment by mover5** [comment]
I would imagine this is similar to the issue I just opened where boolean flags that aren't sticky remain "true" on subsequent calls inside a REPL:
https://github.com/adamabdelhamed/PowerArgs/issues/92

**Comment by adamabdelhamed** [comment]
This is similar to #92, but the fix is a little more complex than the pull request provided here.  That issue is now fixed.
