### ISSUE TITLE
Multiple arguments

### ISSUE THREAD

**Issue by HakanL** [adamabdelhamed/PowerArgs#88]
Is there a way to allow the user to specify multiple arguments (for example Test.exe -srv my.server.com -srv someone.else.com)?

**Comment by pcKris** [comment]
@HakanL, is there a reason you cant just make the -svr a list?
Power args supports List<string> Server then you can do -svr server1.com,server2.com
(syntax may not be 100% right but i believe that's right or close to it and i have done this in the past)

**Comment by HakanL** [comment]
I see, I didn't try that, but that works. However it would be nice with an option to do multiple arguments when you can't easily use a delimiter.

**Comment by pcKris** [comment]
@HakanL can you give an example?
the usage your showing above feels off. Also what would it map to? (ie: what would the class property look like?)

**Comment by HakanL** [comment]
I would have a list/array in the class property, so as an option it could allow multiple arguments with the same key which would be added to the list. Another example is in Linux where you can do multiple -v -v -v to increase verbose level. Maybe this would need a new attribute to allow this behavior, but it would be a good feature to have in PowerArgs IMO.

**Comment by pcKris** [comment]
I could see how that may make some lists a little clearer in the command line call. 
Maybe the Author will throw it in for you, he is really responsive when he has the time.

Hopefully my recommendation above gets you going in the mean time?

**Comment by HakanL** [comment]
Yes it did, thank you!

**Comment by adamabdelhamed** [comment]
I don't think I'm going to make this change.  I standardized on the approach @pcKris mentioned (thanks for helping) because that's how lots of apps support lists and because that's the format windows uses when a list of files is dragged onto an exe.  @HakanL, after trying the recommended approach are you happy or do you feel like it was a workaround?

**Comment by HakanL** [comment]
I'm fine, but I still think it would be a nice feature to have as an option.
