### ISSUE TITLE
Allow us to provide our own way of instantiating objects

### ISSUE THREAD

**Issue by pauldotknopf** [adamabdelhamed/PowerArgs#90]
PowerArgs uses `Activator.CreateInstance` internally all over the place. If we can consolidate all the usages into a single interface/service that can be changed, users could provide their own creator that can resolve types from containers (IoC).

**Comment by adamabdelhamed** [comment]
This is a great idea.  I'll consider this for an upcoming release.  I'll be doing one this weekend so maybe it makes it in.
