### ISSUE TITLE
In REPL, setting a boolean flag can never be turned off

### ISSUE THREAD

**Issue by mover5** [adamabdelhamed/PowerArgs#92]
If I am in a REPL prompt, and my action has a boolean flag, the following happens:

public boolean Force {get;set;}

doaction -force
The action will execute and force == true

Now, in the same REPL,
doaction
The action will execute and force is still true. Should be false.

**Comment by mover5** [comment]
Also, to be clear. The boolean flag is not attributed with [StickyArg]

**Comment by K2** [comment]
Me personally I'd prefer that type of behavior than how everything is re-initialized per run.  Do you have a default=false?  Are you on the dev branch?  This may be fixed there since my bool's seem to be fine.

**Comment by mover5** [comment]
Using [ArgDefaultValue(false)] works, but it just seems weird that you would have to do that. To me, my commands should be separate from each other and the arguments shouldn't persist over between executions. If that is a behavior you want, there is an explicit attribute to do that: [StickyArg]
