### ISSUE TITLE
Args.Parse`1 returns null

### ISSUE THREAD

**Issue by jpierson** [adamabdelhamed/PowerArgs#93]
I have a simple test case which I cannot get to work.

``` c#
[ArgExceptionBehavior(ArgExceptionPolicy.StandardExceptionHandling)]
private class ProgramArgs
{
    public string MyArg { get; set; }
}
```

``` c#
static void Main(string[] args)
{
    var typedArgs = Args.Parse<ProgramArgs>(args);
    Console.WriteLine("Parse returned " + typedArgs == null ? "null" : "a value");
}
```

I'm using version `2.7.1.0` from NuGet and project is .NET 4.5.2.

**Comment by workabyte** [comment]
@jpierson 
what is the value for args? 
what happens? 
what did you expect to happen?

I'll see if i can give you a hand

**Comment by adamabdelhamed** [comment]
In your example, typedArgs will never be null.  typedArgs.Myarg will be null if the user did not specify a value for it.

**Comment by adamabdelhamed** [comment]
No repro
