### ISSUE TITLE
Any plans to migrates it to the .NET Core?

### ISSUE THREAD

**Issue by g0194776** [adamabdelhamed/PowerArgs#96]

**Comment by adamabdelhamed** [comment]
I'm doing work on this project every few months.  As long as there aren't too many active requests I might be able to look at this in the next batch.

I'll have to see what's different about that environment though (e.g. which libraries / APIs are not available) before committing.

**Comment by g0194776** [comment]
thanks a lot, dude.
I'm waiting for it.
